name: Auto Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  eslint-review:
    name: Run ESLint on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and output to file
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx -f json -o eslint-report.json

      - name: Annotate pull request with ESLint results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint-report.json
